project:
  type: website

website:
  title: "AGO-Data-Project"
  navbar:
    left:
      - text: "Data Analytics"
        href: ""
      - text: "Written report"
        href: ""
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Our Group
      - icon: github
        href: https://github.com/junhao2309/AGO-Data-Project
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

